# Minimal runtime configuration for papersys
# Validate with: uv run --no-progress python -m papersys.cli config check --format text
# Inspect schema: uv run --no-progress python -m papersys.cli config explain

# Legacy/general settings
data_root = "./data"
scheduler_enabled = true
embedding_models = ["jasper_v1"]
logging_level = "INFO"

# Scheduler configuration
[scheduler]
enabled = true
timezone = "Asia/Shanghai"

[scheduler.recommend_job]
enabled = true
name = "recommendation-pipeline"
cron = "0 5 * * *" # Daily at 5 AM local time

[scheduler.summary_job]
enabled = true
name = "summary-pipeline"
cron = "0 6 * * *" # Daily at 6 AM local time

# Recommendation pipeline configuration
[recommend_pipeline.data]
categories = ["cs.CL", "cs.CV", "cs.AI", "cs.LG", "stat.ML"]
embedding_columns = ["jasper_v1", "conan_v1"]
preference_dir = "./preference"
embed_repo_id = "lyk/ArxivEmbedding"
content_repo_id = "lyk/ArxivContent"
cache_dir = "./cache"
background_start_year = 2024
preference_start_year = 2023

[recommend_pipeline.trainer]
seed = 42
bg_sample_rate = 5.0

[recommend_pipeline.trainer.logistic_regression]
C = 1.0
max_iter = 1000

[recommend_pipeline.predict]
last_n_days = 7
start_date = ""
end_date = ""
high_threshold = 0.85
boundary_threshold = 0.6
sample_rate = 0.001
output_path = "./recommendations.parquet"

# Summary pipeline configuration
[summary_pipeline.pdf]
output_dir = "./pdfs"
delay = 3
max_retry = 3
model = "deepseek-r1"
language = "zh"
enable_latex = false
acceptable_cache_model = ["grok*", "deepseek*", "gemini*"]

# LLM configurations
[[llms]]
alias = "deepseek-r1"
name = "deepseek-reasoner"
base_url = "https://api.deepseek.com"
api_key = "env:DEEPSEEK_API_KEY"
temperature = 0.7
top_p = 0.8
num_workers = 10
native_json_schema = false

[[llms]]
alias = "gemini-2.5-flash"
name = "gemini-2.5-flash-preview-04-17"
base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key = "env:GEMINI_API_KEY"
temperature = 0.1
top_p = 0.8
num_workers = 10
reasoning_effort = "high"
native_json_schema = true